# Generated by Django 5.0.1 on 2024-01-21 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=511)),
                ('city', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_url', models.CharField(max_length=511)),
                ('cat_name', models.CharField(max_length=127)),
                ('image_url', models.CharField(max_length=127)),
                ('cat_age', models.IntegerField()),
                ('cat_sex', models.CharField(max_length=5)),
                ('added_date', models.DateTimeField(max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.source')),
            ],
        ),
    ]
